name: paig

x-service-defaults: &service-defaults
  restart: unless-stopped
  networks: [ paig ]

services:
  tgbot:
    <<: *service-defaults
    container_name: tgbot
    build:
      context: ./src/bot
      dockerfile: ./build/Dockerfile
    env_file:
      - ./src/bot/.env
      - ./src/postgres/.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    <<: *service-defaults
    container_name: postgres
    build:
      context: ./src/postgres
      dockerfile: ./build/Dockerfile
      args:
        ADDITIONAL_LANGUAGE: ${ADDITIONAL_LANGUAGE}
    env_file: [ ./src/postgres/.env ]
    ports: [ 127.0.0.1:54320:5432 ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/postgres/build/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

  stylegan-generator:
    <<: *service-defaults
    container_name: stylegan-generator
    build:
      context: ./src/stylegan
      dockerfile: ./build/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ipc: host

networks:
  paig:
    name: paig

volumes:
  postgres-data:
    name: postgres-data
